### ISSUE TITLE
Clarify job priority

### ISSUE THREAD

**Issue by cadop** [arcs-njit-edu/Docs#17]
The explanation for job priorities and how it is counted against SU's could be more explicit.  
https://arcs-njit-edu.github.io/Docs/Policies/wulver_policies/#job-priorities

- Does it refer specifically to: `#SBATCH --qos=low`

- How can a user query their current usage/allocation available? 

It's understandable the infrastructure is in beta, re: `More details on calculating SUs for GPUs, high memory nodes, etc… will be provided at a later date`. 

- Does the GPU SU rule for low priority equal the CPU?

**Comment by alexpacheco** [comment]
The GPU and high memory SU usage is documented at https://arcs-njit-edu.github.io/Docs/Software/slurm/slurm/#using-slurm-on-wulver.

@absrocks Can you check the documentation and edit as appropriate for consistency

**Comment by cadop** [comment]
I see the docs have this in both areas.
